# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x07\x61\x63\x63ount\"7\n\x1fGetLoginVerificationCodeRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\"\"\n GetLoginVerificationCodeResponse\"b\n\x0cLoginRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x19\n\x11verification_code\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\"7\n\rLoginResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x15\n\rauthorization\x18\x02 \x01(\t\"\x18\n\x16LoginByOneClickRequest\"A\n\x17LoginByOneClickResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x15\n\rauthorization\x18\x02 \x01(\t\"v\n\x11MyProfileResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x12\n\navatar_url\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\x03\x12\x0b\n\x03\x62io\x18\x07 \x01(\t\x12\r\n\x05level\x18\t \x01(\x03\"\x15\n\x13RefreshTokenRequest\"-\n\x14RefreshTokenResponse\x12\x15\n\rauthorization\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLOGINVERIFICATIONCODEREQUEST']._serialized_start=26
  _globals['_GETLOGINVERIFICATIONCODEREQUEST']._serialized_end=81
  _globals['_GETLOGINVERIFICATIONCODERESPONSE']._serialized_start=83
  _globals['_GETLOGINVERIFICATIONCODERESPONSE']._serialized_end=117
  _globals['_LOGINREQUEST']._serialized_start=119
  _globals['_LOGINREQUEST']._serialized_end=217
  _globals['_LOGINRESPONSE']._serialized_start=219
  _globals['_LOGINRESPONSE']._serialized_end=274
  _globals['_LOGINBYONECLICKREQUEST']._serialized_start=276
  _globals['_LOGINBYONECLICKREQUEST']._serialized_end=300
  _globals['_LOGINBYONECLICKRESPONSE']._serialized_start=302
  _globals['_LOGINBYONECLICKRESPONSE']._serialized_end=367
  _globals['_MYPROFILERESPONSE']._serialized_start=369
  _globals['_MYPROFILERESPONSE']._serialized_end=487
  _globals['_REFRESHTOKENREQUEST']._serialized_start=489
  _globals['_REFRESHTOKENREQUEST']._serialized_end=510
  _globals['_REFRESHTOKENRESPONSE']._serialized_start=512
  _globals['_REFRESHTOKENRESPONSE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
