# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apiv2.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'apiv2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61piv2.proto\x12\x05\x61piv2\"\x13\n\x11PcAdConfigRequest\"`\n\x0ePcAdConfigItem\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\naward_unix\x18\x02 \x01(\x03\x12\r\n\x05level\x18\x03 \x01(\x03\x12\x10\n\x08is_watch\x18\x04 \x01(\x08\x12\r\n\x05title\x18\x05 \x01(\t\"\x86\x01\n\x13PcAdConfigLevelItem\x12\r\n\x05level\x18\x01 \x01(\x03\x12#\n\x04list\x18\x02 \x03(\x0b\x32\x15.apiv2.PcAdConfigItem\x12\x11\n\twatch_cnt\x18\x03 \x01(\x03\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x0b\n\x03tag\x18\x05 \x01(\t\x12\r\n\x05title\x18\x06 \x01(\t\">\n\x12PcAdConfigResponse\x12(\n\x04list\x18\x01 \x03(\x0b\x32\x1a.apiv2.PcAdConfigLevelItem\"<\n\x19PcAdCallbackBackupRequest\x12\r\n\x05\x61\x64_id\x18\x01 \x01(\t\x12\x10\n\x08\x62usiness\x18\x02 \x01(\x03\"/\n\x1aPcAdCallbackBackupResponse\x12\x11\n\tis_verify\x18\x01 \x01(\x08\"\x1e\n\x1cGetUserRemainDurationRequest\"\xb0\x01\n\x1dGetUserRemainDurationResponse\x12\x1b\n\x13vip_duration_second\x18\x01 \x01(\x03\x12\x1c\n\x14\x66ree_duration_second\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x13\n\x0bpause_state\x18\x04 \x01(\x03\x12\x16\n\x0eis_first_award\x18\x05 \x01(\x08\x12\x14\n\x0cpc_vip_state\x18\x07 \x01(\x03\".\n\x17UpdatePauseStateRequest\x12\x13\n\x0bpause_state\x18\x01 \x01(\x03\"\x1a\n\x18UpdatePauseStateResponse\"\x1c\n\x1aMobilePcProductListRequest\"\x15\n\x13MobilePcProductItem\"G\n\x1bMobilePcProductListResponse\x12(\n\x04list\x18\x01 \x03(\x0b\x32\x1a.apiv2.MobilePcProductItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apiv2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PCADCONFIGREQUEST']._serialized_start=22
  _globals['_PCADCONFIGREQUEST']._serialized_end=41
  _globals['_PCADCONFIGITEM']._serialized_start=43
  _globals['_PCADCONFIGITEM']._serialized_end=139
  _globals['_PCADCONFIGLEVELITEM']._serialized_start=142
  _globals['_PCADCONFIGLEVELITEM']._serialized_end=276
  _globals['_PCADCONFIGRESPONSE']._serialized_start=278
  _globals['_PCADCONFIGRESPONSE']._serialized_end=340
  _globals['_PCADCALLBACKBACKUPREQUEST']._serialized_start=342
  _globals['_PCADCALLBACKBACKUPREQUEST']._serialized_end=402
  _globals['_PCADCALLBACKBACKUPRESPONSE']._serialized_start=404
  _globals['_PCADCALLBACKBACKUPRESPONSE']._serialized_end=451
  _globals['_GETUSERREMAINDURATIONREQUEST']._serialized_start=453
  _globals['_GETUSERREMAINDURATIONREQUEST']._serialized_end=483
  _globals['_GETUSERREMAINDURATIONRESPONSE']._serialized_start=486
  _globals['_GETUSERREMAINDURATIONRESPONSE']._serialized_end=662
  _globals['_UPDATEPAUSESTATEREQUEST']._serialized_start=664
  _globals['_UPDATEPAUSESTATEREQUEST']._serialized_end=710
  _globals['_UPDATEPAUSESTATERESPONSE']._serialized_start=712
  _globals['_UPDATEPAUSESTATERESPONSE']._serialized_end=738
  _globals['_MOBILEPCPRODUCTLISTREQUEST']._serialized_start=740
  _globals['_MOBILEPCPRODUCTLISTREQUEST']._serialized_end=768
  _globals['_MOBILEPCPRODUCTITEM']._serialized_start=770
  _globals['_MOBILEPCPRODUCTITEM']._serialized_end=791
  _globals['_MOBILEPCPRODUCTLISTRESPONSE']._serialized_start=793
  _globals['_MOBILEPCPRODUCTLISTRESPONSE']._serialized_end=864
# @@protoc_insertion_point(module_scope)
